# Intro to Pytorch

In [4]:
%matplotlib inline
import torch
import numpy as np

## Tensor Basics

### Initializing a Tensor
Tensors can be initialized in various ways. Take a look at the following examples:

**Directly from data**

Tensors can be created directly from data. The data type is automatically inferred.

In [5]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

**From a NumPy array**

Tensors can be created from NumPy arrays and vice versa. Since, numpy 'np_array' and tensor 'x_np' share the same memory location here, changing the value for one will change the other.

In [6]:
np_array = np.array(data)
x_np=torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [7]:
print(f"Numpy np_array value: \n {np_array} \n")
print(f"Tensor x_np value: \n {x_np} \n")

Numpy np_array value: 
 [[1 2]
 [3 4]] 

Tensor x_np value: 
 tensor([[1, 2],
        [3, 4]], dtype=torch.int32) 



In [8]:
np.multiply(np_array, 2, out=np_array)

print(f"Numpy np_array after * 2 operation: \n {np_array} \n")
print(f"Tensor x_np value after modifying numpy array: \n {x_np} \n")

Numpy np_array after * 2 operation: 
 [[2 4]
 [6 8]] 

Tensor x_np value after modifying numpy array: 
 tensor([[2, 4],
        [6, 8]], dtype=torch.int32) 



**From another tensor:**

The new tensor retains the properties (shape, data type) of the argument tensor, unless explicitly overridden.

In [9]:
x_ones=torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [10]:
x_rand=torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.8677, 0.0168],
        [0.1675, 0.0133]]) 



**With random or constant values:**

shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor. Shape shows the number of rows and columns in the tensor. 

*E.g. shape = (# of rows, # of columns).*

In [11]:
shape=(2,1,)
rand_tensor=torch.rand(shape)
ones_tensor=torch.ones(shape)
zeros_tensor=torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.5735],
        [0.8533]]) 

Ones Tensor: 
 tensor([[1.],
        [1.]]) 

Zeros Tensor: 
 tensor([[0.],
        [0.]]) 



### Tensor Attributes

Tensor attributes describe their shape, data type, and the device on which they are stored.

In [12]:
tensor=torch.rand(2,4,2)

print(f"Shape of tensor: \n {tensor} \n")

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: 
 tensor([[[0.3797, 0.3502],
         [0.3792, 0.4824],
         [0.2046, 0.1192],
         [0.4321, 0.9628]],

        [[0.7224, 0.6113],
         [0.2676, 0.6636],
         [0.8825, 0.1988],
         [0.0121, 0.0192]]]) 

Shape of tensor: torch.Size([2, 4, 2])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Tensor Operations

There are more than 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing). For sampling and reviewing, you'll find a comprehensive description here.

Each of these operations can be run on the GPU (at typically higher speeds than on a CPU).

- CPUs have up to 16 cores. Cores are units that do the actual computation. Each core processes tasks in a sequential order (one task at a time).
- GPUs have 1000s of cores. GPU cores handle computations in parallel processing. Tasks are divided and processed across the different cores. That's what makes GPUs faster than CPUs in most cases. GPUs perform better with large data than small data. GPU are typically used for high-intensive computation of graphics or neural networks (we'll learn more about that later in the Neural Network unit).
- PyTorch can use the Nvidia CUDA library to take advantage of their GPU cards.



Diagram showing workload between cpu and gpu


By default, tensors are created on the CPU. Tensors can also be computed to GPUs; to do that, you need to move them using the .to method (after checking for GPU availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory

In [13]:
if torch.cuda.is_available():
    tensor=tensor.to('cuda')

In [16]:
tensor = torch.ones(4,4)

print('First row: ',tensor[0])
print('First column: ',tensor[:,0])
print('Last column: ',tensor[...,-1])

tensor[:,1]=0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column:  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#### Joining tensors

You can use *torch.cat* to concatenate a sequence of tensors along a given dimension. *torch.stack* is another tensor joining option that is subtly different from *torch.cat*. 
- *torch.stack* stacks a sequence of tensors along a new dimension. It creates new dimension for the tensors. 
- *torch.cat* concatenates the sequence of tensors in the existing dimension.

In [20]:
T1=torch.cat([tensor,tensor,tensor],dim=1)
print(T1)

T2=torch.stack([tensor,tensor,tensor],dim=1)
print(T2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


#### Arithmetic operations

In [30]:
y1=tensor @ tensor.T
y2=tensor.matmul(tensor.T)

y3=torch.rand_like(tensor)
torch.matmul(tensor,tensor.T,out=y3)


print(y1)
print(y2)
print(y3)


z1=tensor*tensor
z2=tensor.mul(tensor)

z3=torch.rand_like(tensor)
torch.mul(tensor,tensor,out=z3)

print(z1)
print(z2)
print(z3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#### Single-element tensors
if you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item()

In [33]:
print(tensor,tensor.shape)
agg=tensor.sum()
print(agg)
agg_item=agg.item()
print(agg_item,type(agg_item))

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) torch.Size([4, 4])
tensor(12.)
12.0 <class 'float'>


#### In-place operations

Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.

> Note: In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.



In [34]:
print(tensor,"\n")

tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


### Bridge with NumPy
Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

**Tensor to NumPy array**

In [35]:
t=torch.ones(5)

print(f"t: {t}")
n=t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


Change in tensor reflects in the NumPy array.

In [36]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


**NumPy array to Tensor**

In [38]:
n=np.ones(5)
t=torch.from_numpy(n)

"""#Changes in numpy array reflects in tensor as well"""

np.add(n,1,out=n)
print(f"t: {t}")
print(f"n: {n}")


t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
